[PATH]
movies_md = './data/movies_metdata.parquet'
interactions = './data/interactions.parquet'

[VARIABLES]
columns_list = ['genres','actors','director','country']
date= date_columns_list['day','month','year']

[PARAMS]
MAX_DATE = interactions['last_watch_dt'].max()
MIN_DATE = interactions['last_watch_dt'].min()
TEST_INTERVAL_DAYS = 14
TEST_MAX_DATE = MAX_DATE - dt.timedelta(days = TEST_INTERVAL_DAYS)