[PATH]
interactions_link = 'item2item/data/interactions.parquet'
movies_md_link = 'item2item/data/movies_metdata.parquet'
movies_rd_link = 'item2item/data/Movies_r_d.xlsx'
movies_rd_upd_link = 'item2item/data/movies_rd.parquet'
int_coef_link = 'item2item/data/int_coef.parquet'
movies_md_upd_link = './data/movies_md_upd.parquet'
interactions_upd_link = './data/interactions_upd.parquet'
cos_sim_md_link = 'item2item/matrix/cos_sim_md.pkl'
cos_sim_desc_link = 'item2item/matrix/cos_sim_desc.pkl'

[VARIABLES]
columns_list = ['genres','actors','director','country']


